apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    name: redis
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
