#!/bin/sh

sudo /usr/local/cloud/bin/xhyve \
-U 3646C502-7C09-4259-B71D-4B4BB447D6A6 \
-A \
-c 4 \
-m 4G \
-s 0,hostbridge \
-s 2,virtio-net \
-s 4,virtio-blk,ubuntu.img \
-s 5,virtio-blk,k3s.img \
-s 31,lpc \
-l com1,stdio \
-f 'kexec,vmlinuz,initrd,earlyprintk=serial console=ttyS0 root=/dev/vda1'
