#cloud-config
hostname: cloud
growpart:
  mode: auto
  devices:
  - /
package_update: true
packages:
- nfs-common
- unzip
write_files:
- path: /etc/profile.d/editor.sh
  owner: root:root
  permissions: '0644'
  content: |
    export EDITOR=vi
- path: /usr/local/bin/send-ips
  owner: root:root
  permissions: '0755'
  content: |
    #!/bin/sh
    vm_ip=$(hostname -I | awk '{ print $1 }')
    mac_ip=$(echo $vm_ip | cut -d . -f 1-3).1

    cat <<EOF | nc -q 1 $mac_ip 1234
    vm_ip=$vm_ip
    mac_ip=$mac_ip
    EOF
- path: /lib/systemd/system/send-ips.service
  owner: root:root
  permissions: '0644'
  content: |
    [Unit]
    Description=Send Ips.
    After=network.target

    [Service]
    ExecStart=/usr/local/bin/send-ips

    [Install]
    WantedBy=multi-user.target
- path: /usr/local/bin/pack-img
  owner: root:root
  permissions: '0755'
  content: |
    #!/bin/sh
    curl -sfL https://get.k3s.io | sh -
    cat <<-EOF >> /etc/rancher/k3s/registries.yaml
      mirrors:
        "cloud:32000":
          endpoint:
          - "http://cloud:32000"
    EOF
    service k3s restart

    curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip'
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf awscliv2.zip awscliv2 aws
    apt remove -y unzip

    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
    sed -i 's/nullok_secure/nullok/' /etc/pam.d/common-auth
    service sshd reload

    passwd -d root
    touch /root/.hushlogin

    apt autoremove -y

    systemctl enable send-ips

    k3s-killall.sh
    systemctl stop \
    syslog.socket \
    systemd-journald.socket \
    systemd-journald-dev-log.socket \
    systemd-journald-audit.socket \
    syslog.socket \
    rsyslog.service \
    unattended-upgrades.service

    apt clean
    rm -rf \
    /root/.cache \
    /var/log/* \
    /tmp/*

    mount -o ro,remount /
    zerofree /dev/vda1

    rm $0
    halt
runcmd:
- pack-img
