#!/bin/sh

ubuntu_url=https://cloud-images.ubuntu.com/bionic/current

curl $ubuntu_url/bionic-server-cloudimg-amd64.img > install.img
curl $ubuntu_url/unpacked/bionic-server-cloudimg-amd64-vmlinuz-generic > vmlinuz
curl $ubuntu_url/unpacked/bionic-server-cloudimg-amd64-initrd-generic > initrd
