apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
