#!/bin/sh

etc_path=/usr/local/etc/nginx

pkg install -y \
nginx \
py37-certbot \
py37-certbot-nginx \
py37-certbot-dns-cloudflare

for target in proxy.conf nginx.conf hosts.map; do
	cp /mnt/lib/ingress/$target $etc_path
done
touch $etc_path/hosts
