#!/bin/sh

bin/bundle config build.nokogiri --use-system-libraries
if [ "$RAILS_ENV" = production ]; then
  bin/bundle config set without 'development test'
fi
bin/bundle install

if [ "$RAILS_ENV" = production ]; then
  SECRET_KEY_BASE=0 bin/rails assets:precompile
fi

if [ "$RAILS_ENV" != production ]; then
  bin/spring server >log/spring.log 2>&1 &
fi
mkdir -p tmp/pids
if [ "$RAILS_ENV" != production ]; then
  rm -f tmp/pids/server.pid
fi
bin/rails server
