apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    name: rails
spec:
  type: NodePort
  selector:
    name: rails
  ports:
    - name: rails
      port: 3000
      nodePort: {{ rails_port }}
