runcmd:
  - sudo install-microk8s
  - sudo apt install -y nfs-common
  - sudo mkdir /rails
write_files:
  - path: /usr/local/bin/install-microk8s
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/sh
      snap install microk8s --classic
      cat <<EOF >> /var/snap/microk8s/current/args/kube-apiserver

      # Enable insecure connections
      --insecure-bind-address=0.0.0.0
      --insecure-port=8080
      EOF
      microk8s.status --wait-ready
      microk8s.enable dns registry
