#!/bin/sh

prefix_path() {
	echo "/mnt/$1"
}

case $1 in
install)

	chown root:root $0
	chmod +x $0
	mv $0 /usr/local/bin/cloud
	apt-get install -y nfs-common
	snap install microk8s --classic
	cat <<-EOF >> /var/snap/microk8s/current/args/kube-apiserver

	# Enable insecure connections
	--insecure-bind-address=0.0.0.0
	--insecure-port=8080
	EOF
	microk8s.status --wait-ready
	microk8s.enable dns registry

;;
app)

	case $2 in
	add)

		mount_path=$(prefix_path $3)
		echo "$4:$5\t$mount_path\tnfs defaults\t0 0" >> /etc/fstab
		mkdir -p $mount_path
		mount $mount_path

	;;
	remove)

		mount_path=$(prefix_path $3)
		umount $mount_path
		sed -i '' "/$3/d" /etc/fstab
		rmdir $mount_path

	;;
	esac

;;
esac
