#!/bin/sh

ssl_path=/ssl

if [ $CLOUD_CONTEXT = local ]; then
	cert_path=$ssl_path/fullchain.pem
	key_path=$ssl_path/privkey.pem
	req_path=/tmp/req.cnf

	cert_valid() {
		openssl x509 \
		-checkend 86400 \
		-noout \
		-in $cert_path
	}

	cat <<-SSL > $req_path
		[req]
		distinguished_name = req_distinguished_name
		x509_extensions = v3_req
		prompt = no

		[req_distinguished_name]
		C = UY
		ST = MA
		L = Punta del Este
		O = Chi
		OU = IT
		CN = *.cloud.local

		[v3_req]
		keyUsage = critical, digitalSignature, keyAgreement
		extendedKeyUsage = serverAuth
		subjectAltName = @alt_names

		[alt_names]
		DNS.1 = *.cloud.local
	SSL

	if [ ! -f $cert_path ] || ! cert_valid; then
		openssl req \
		-nodes \
		-sha256 \
		-x509 \
		-days 365 \
		-newkey rsa:2048 \
		-out $cert_path \
		-keyout $key_path \
		-config $req_path

		rm $req_path
	fi
else
	ini_path=/tmp/cloudflare.ini
	live_path=/etc/letsencrypt/live/$CLOUD_DOMAIN

	if [ -d $live_path ]; then
		certbot renew
	else
		cat <<-INI > $ini_path
		dns_cloudflare_email = $DNS_USER
		dns_cloudflare_api_key = $DNS_PASS
		INI

		opts="-d $CLOUD_DOMAIN"
		if echo $CLOUD_DOMAIN | grep -qE '^[a-z]+\.[a-z]+$'; then
			opts="$opts -d *.$CLOUD_DOMAIN"
		fi

		certbot certonly \
		$opts \
		-n \
		--agree-tos \
		--email $DNS_USER \
		--dns-cloudflare \
		--dns-cloudflare-credentials $ini_path
	fi
fi
