apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ storage }}
