#!/bin/sh

config_path=/etc/docker/registry/config.yml
htpasswd_path=/etc/docker/registry/htpasswd
cmd="registry serve $config_path"

if [ $CLOUD_CONTEXT = local ]; then
	REGISTRY_HTTP_ADDR=:5000 \
	$cmd
else
	htpasswd -Bbn $USER $PASS > $htpasswd_path

  REGISTRY_AUTH=htpasswd \
	REGISTRY_AUTH_HTPASSWD_REALM=Registry \
	REGISTRY_AUTH_HTPASSWD_PATH=$htpasswd_path \
	$cmd
fi
