apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  type: NodePort
  selector:
    name: {{ name }}
  ports:
  - name: {{ name }}
    port: {{ pod_port }}
    nodePort: {{ cluster_port }}
