{{ render node.service }}
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  replicas: {{ replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - image: {{ repo }}
        name: {{ name }}
        tty: true
        stdin: true
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          value: '{{ master_key }}'
        - name: RAILS_ENV
          value: {{ app_env }}
        - name: RAILS_THREADS
          value: {{ threads }}
        - name: RAILS_WORKERS
          value: '{{ workers }}'
        - name: REDIS_URL
          value: redis://{{ redis_host }}:{{ redis_pod_port }}
{{ render rails.mount }}
