{{ render pod.service }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  replicas: {{ replicas }}
  strategy:
    type: {{ strategy }}
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
      - image: {{ image }}
        imagePullPolicy: {{ pull }}
        name: {{ name }}
        tty: true
        stdin: true
        env:
        - name: RAILS_MASTER_KEY
          value: '{{ master_key }}'
        - name: RAILS_ENV
          value: {{ cloud_env }}
        - name: RAILS_THREADS_MIN
          value: '{{ threads_min }}'
        - name: RAILS_THREADS_MAX
          value: '{{ threads_max }}'
        - name: RAILS_WORKERS
          value: '{{ workers }}'
        - name: REDIS_URL
          value: {{ redis_url }}
        - name: RAILS_RELATIVE_URL_ROOT
          value: {{ cloud_relative_path }}
        volumeMounts:
        - mountPath: /rails
          name: rails
      volumes:
      - name: rails
        hostPath:
          path: {{ app_path }}
