#!/bin/sh

build_mount_path() {
	printf "/mnt/$1"
}

find_mac_ip() {
	echo $(ip -4 -o addr show enp0s2 | awk '{ print $4 }' | sed 's/[0-9]*\/.*//')1
}

case $1 in
install)

	apt-get install -y nfs-common
	snap install microk8s --classic
	cat <<-EOF >> /var/snap/microk8s/current/args/kube-apiserver

	# Enable insecure connections
	--insecure-bind-address=0.0.0.0
	--insecure-port=8080
	EOF
	microk8s.status --wait-ready
	microk8s.enable dns registry
	mac_ip=$(find_mac_ip)
	cat <<-EOF >> /etc/hosts

		# Host alias
		$mac_ip mac
	EOF

;;
add)

	mount_path=$(build_mount_path $2)
	cat <<-EOF >> /etc/fstab
		mac:$2	$mount_path	nfs defaults	0 0
	EOF
	mkdir -p $mount_path
	mount $mount_path

;;
remove)

	mount_path=$(build_mount_path $2)
	umount $mount_path
	sed -i '' "/$mount_path/d" /etc/fstab
	rmdir $mount_path

;;
esac
