#!/bin/sh

build_mount_path() {
	printf "/mnt/$1"
}

case $1 in
install)

	apt-get install -y nfs-common
	snap install microk8s --classic
	cat <<-EOF >> /var/snap/microk8s/current/args/kube-apiserver

	# Enable insecure connections
	--insecure-bind-address=0.0.0.0
	--insecure-port=8080
	EOF
	microk8s.status --wait-ready
	microk8s.enable dns registry

;;
uninstall)

	apt-get purge -y nfs-common
	snap remove --purge microk8s

;;
add)

	mount_path=$(build_mount_path $2)
	printf "mac:$2\t$mount_path\tnfs defaults\t0 0\n" >> /etc/fstab
	mkdir -p $mount_path
	mount $mount_path

;;
remove)

	mount_path=$(build_mount_path $2)
	umount $mount_path
	sed -i '' "/$mount_path/d" /etc/fstab
	rmdir $mount_path

;;
esac
