write_files:
  - path: /usr/local/bin/cloud-install
    owner: root:root
    permissions: '0755'
    content: |
      apt-get install -y nfs-common
      snap install microk8s --classic
      cat <<-EOF >> /var/snap/microk8s/current/args/kube-apiserver

      # Enable insecure connections
      --insecure-bind-address=0.0.0.0
      --insecure-port=8080
      EOF
      microk8s.status --wait-ready
      microk8s.enable dns registry
      mac_ip=$(ip -4 -o addr show enp0s2 | awk '{ print $4 }' | sed 's/[0-9]*\/.*//')1
      cat <<-EOF >> /etc/hosts

      	# Host alias
      	$mac_ip mac
      EOF
