{{ render local.claim }}
---
{{ render pod.service }}
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  strategy:
    type: {{ strategy }}
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
      - image: {{ repo }}
        name: {{ name }}
        env:
        - name: POSTGRES_USER
          value: {{ user }}
        - name: POSTGRES_PASSWORD
          value: '{{ pass }}'
        - name: POSTGRES_DB
          value: {{ db }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ name }}
      volumes:
      - name: {{ name }}
        persistentVolumeClaim:
          claimName: {{ name }}
