#!/bin/sh

apt update
apt install \
git-core \
curl \
tzdata \
nodejs \
yarn \
build-essential \
libssl-dev \
libreadline-dev \
libyaml-dev \
libxml2-dev \
libxslt1-dev
echo 'gem: --no-document' > /etc/gemrc

name=ruby-2.5.3
path=/tmp/$name
curl http://cache.ruby-lang.org/pub/ruby/2.5/$name.tar.gz | tar -xzf - -C /tmp
(cd $path &&
./configure --disable-install-doc &&
make &&
make install)
rm -rf $path
gem update --system --no-document
gem install bundler --no-document
bundle config build.nokogiri --use-system-libraries
